### ISSUE TITLE
Change MySQL Command To 'mariadb'

### ISSUE THREAD

**Issue by cerbervs** [tpope/vim-dadbod#140]
This warning has been popping up for a while.
![image](https://github.com/tpope/vim-dadbod/assets/55473544/3c9fa567-9c7d-4e3a-95de-4617b0124552)

Would it be appropriate to change the MySQL command to `mariadb` in preparation for the future release?
I can fork this and make a pull request if it's the right time to do this.

**Comment by anton-fomin** [comment]
I have the same problem, but I don't think that the command should be changed. As far as I can see the problem happens when you have `mariadb` client installed, then it creates a symlink `mysql` -> `mariadb`, but produces this warning in case `mysql` command used.
The current implementation is valid for MySQL users.
So I believe it would be more correct to create a separate adapter for mariadb.

**Comment by psaikido** [comment]
This issue is a show-stopper for me.

**Comment by cerbervs** [comment]
@FC-Zer0x1 didn't see that. Will close this issue.
