### ISSUE TITLE
One line outputs of successful commands do not appear in preview window

### ISSUE THREAD

**Issue by oliverralbertini** [tpope/vim-dadbod#47]
Simple commands that run successfully and return one line of output do not show up in the preview window (*.dbout). If they return more than one line or error out in some way, they appear in the preview window.

I think it's a better user experience if all output goes to the preview file.

To reproduce, commands like `drop table foo;` can be run. Note that running two drop commands  together results in this printed in the preview window:
```
DROP TABLE
DROP TABLE
```

**Comment by tpope** [comment]
I think it's a better experience if I don't have to close a preview window for every dumb command with content free output. Which is why I bent over backwards to implement this behavior. It's not just "one line" output, it's adapter specific logic, and your double drop example has me considering extending the PostgreSQL logic to multiple lines.

But feel free to send a PR to make it opt out if it bothers you that much.
