### ISSUE TITLE
Add mapping for tabbing through cells

### ISSUE THREAD

**Issue by skbolton** [tpope/vim-dadbod#50]
First off thanks for this plugin I never thought the query tool of my dreams would be in vim! I was wondering how you would feel about adding a mapping in the preview window to tab back and forth between cells. The use case for me is that I am working in a new database where I am not yet familiar with the column names so I don't know what to search for yet. 

So far I have just done a lot of `f |` and `F|` to jump between the cells but I can't help how nice it would be to have maybe tab to move forward and delete to move backward?

**Comment by tpope** [comment]
The problem is it's hard to do robustly because it's raw output from command line tools with varying semantics. Some tools use `|`, some use a Unicode character, some like Mongo don't do tabular output at all.

I also wouldn't want to use the tab key, because that's just `<C-I>` in Vim, and as nearly useless as that behavior is, I don't want to override it.

Right now I'm inclined to think the solution is you should pursue is globally mapping a key to `f|l` or something like that.

**Comment by skbolton** [comment]
Sounds good thanks for letting me know the constraints!
