### ISSUE TITLE
Put the SQL query in the result buffer

### ISSUE THREAD

**Issue by bogdan** [tpope/vim-dadbod#56]
I think it would be convinient to put the executed query in the result window that helps the remember what was queried for in case when navigating between buffers with results still open.

**Comment by kristijanhusak** [comment]
This could maybe help you https://github.com/kristijanhusak/vim-dadbod-ui

**Comment by tssm** [comment]
@bogdan I have a simple solution: for every query two temporary files are created: one contains the query itself (whose name ends in `.sql`) and the other contains the result (whose name ends with `.dbout`). You can get the path of the latter with `expand('%')` when the focus is in the result buffer, so using a bit of Vim script you can show it on the status line:

`match(expand('%'), '.*\.dbout$') > -1 ? join(readfile(expand('%:r') . '.sql'))`

I think this is better than adding it to the buffer content because it's always visible, even if you scroll down the result buffer

**Comment by tpope** [comment]
The more precise way to get there is to check `b:db_input`, which will work even if the database doesn't use `.sql`.

A more elegant way to review the query would be nice, but I think putting it in the same buffer is a nonstarter, if only for syntax highlighting related reasons.
