### ISSUE TITLE
Bang Version in Documentation and op_exec

### ISSUE THREAD

**Issue by aoswalt** [tpope/vim-dadbod#57]
Is the bang version of the command intended to be private?

I noticed that the option exists in the code, but there is no documentation. I would be happy to add it if wanted.

Relatedly, could a bang version of op_exec exist for mappings?

**Comment by tpope** [comment]
> Is the bang version of the command intended to be private?

I added it for completeness sake but was hesitant to commit to supporting it. Not much has changed since then.

> I noticed that the option exists in the code, but there is no documentation. I would be happy to add it if wanted.

No for now.
 
> Relatedly, could a bang version of op_exec exist for mappings?

See, one of the problems with `:DB!` is now I have to figure out a naming scheme when I can't use bangs. I don't want to deal with this right now, but if you want this, you're not blocked by me:

```vim
function! MyOpExec(...) abort
  if !a:0
    set opfunc=MyOpExec
    return 'g@'
  endif
  exe db#range(a:1) . '!'
endfunction
```
