### ISSUE TITLE
`jq:` adapter - no idea how to use it

### ISSUE THREAD

**Issue by vlcinsky** [tpope/vim-dadbod#85]
@odnoletkov 

The #73 claims to add `jq` adapter. As i use `jq` very often, I appreciate this option.

Anyway, I did not find a way to get any result from it.

Info:
- neovim v0.4.4
- OS: Debian 10 Stretch
- jq-1.5-1-a5b5cbe

My understanding of expected usage is:
- configure adapter to point to JSON file to process, e.g. to `jq:data.json`
- call DB with queries such as `.` (to simply pretty print the data), `keys` to list keys`, `length` to find length of an array etc.

What I have done:
- set env var `export DATABASE_URL=jq:///home/javl/devel/tis/db/data.json` or to `jq:data.json`
- run `:DB .`

The only result I get is `jq: Could not open /dev/stdin: No such device or address`

**Comment by odnoletkov** [comment]
Probably `:DB .` is ambiguous because dadbod parses dot as [url] from the `:DB [url] {cmd}` syntax, not {cmd} from `:DB {cmd}` shortcut.

Does it work if you try unambiguous command, for example `:DB "hello word"`?

This fixes it for me although I'm seeing a different error for your original repro steps (using vanilla Vim on macOS)

**Comment by vlcinsky** [comment]
@odnoletkov I have tested proposed `:DB "hello word"` and it complains with `jq: Could not open /dev/stdin: No such device or address`

Could you show any real use case which works for you?

Jan

**Comment by odnoletkov** [comment]
`:DB "hello word"` with the $DATABASE_URL setup you listed above works for me.

Also `:DB jq:test.json .` works without any extra setup.

---

`Could not open /dev/stdin` sounds really [strange](https://unix.stackexchange.com/questions/36403/how-portable-are-dev-stdin-dev-stdout-and-dev-stderr), can you check with your shell if you have the symlink?

```
$ ls -l /dev/stdin
lr-xr-xr-x  1 root  wheel  0 Feb 14 20:37 /dev/stdin -> fd/0
```

Also check the output is the same from Vim to ensure shell is set up properly:

    :!ls -l /dev/stdin

**Comment by vlcinsky** [comment]
from console:
```
$ ls /dev/stdin -l
lrwxrwxrwx 1 root root 15 Mar  2 08:59 /dev/stdin -> /proc/self/fd/0
```
and from neovim:
```
:!ls -l /dev/stdin                                                                                                                                                                                                 
lrwxrwxrwx 1 root root 15 Mar  2 08:59 /dev/stdin -> /proc/self/fd/0 
```

**Comment by odnoletkov** [comment]
So I was able to repro the issue, need Neovim and Linux:

```
:echo system('cat /dev/stdin','1')
cat: /dev/stdin: No such device or address
```

Probably caused by difference in how Neovim [implements](https://github.com/neovim/neovim/pull/5502) `system()`. Reprting in https://github.com/neovim/neovim/issues/14049

**Comment by tpope** [comment]
`/dev/stdin` isn't portable, I never should have allowed it. Get rid of that shit and use `input_flag`.

**Comment by odnoletkov** [comment]
I'm having issues with switching to `input_flag`:

1. Underlying command is invoked twice during single `:DB` call:

```
  4 function db#execute_command[21]                                                                                    
  3 db#connect[8]                                                                                                      
  2 <SNR>81_filter[2]                                                                                                  
  1 db#adapter#dispatch[1]                                                                                             
->0 db#adapter#jq#filter 
```

```
  4 function db#execute_command[93]                                                                                    
  3 <SNR>81_filter_write[1]                                                                                            
  2 <SNR>81_filter[2]                                                                                                  
  1 db#adapter#dispatch[1]                                                                                             
->0 db#adapter#jq#filter 
```

Only the second case uses `input_flag`. The first one doesn't and we end up invoking just `jq file.json` which is an error.

2. `input_flag` is currently appended in the end so we end up with:

```
jq file.json --from-file input.jq
```

This is not supported by jq, options should go before files:

```
jq [options...] filter [files...]
```

---

@tpope am I using it wrong?

**Comment by tpope** [comment]
> Only the second case uses `input_flag`. The first one doesn't and we end up invoking just `jq file.json` which is an error.

First case needs to be updated. I guess this is the first time a command has _required_ an input file. I think I would centralize `input_flag` handling in `s:filter()` since every consumer needs it, and pass in a filename as a second argument.
 
> This is not supported by jq, options should go before files.

Ugh, I want to rag on `jq` for this but really this is the problem with shoehorning a utility command into a database interface. I think the solution here is to use the new argument list variant for commands as introduced in https://github.com/tpope/vim-dadbod/commit/d3fce38678e1a10c62eb46ac5bf54dec05cc8803. If an argument list contains `--`, the input flag or flags can be inserted before it.

Cumulatively this isn't a huge task but it isn't a small one either, and I wouldn't fault anyone for bailing on it, but if it doesn't get done by the next release (lol), I think ripping the `jq` adapter out is my plan B. Note that shipping an adapter externally is explicitly supported.
