### ISSUE TITLE
Adapters not properly loading with nightly Neovim

### ISSUE THREAD

**Issue by kristijanhusak** [tpope/vim-dadbod#98]
Neovim nightly updated `&rtp` to not contain folders to plugins. See https://github.com/neovim/neovim/issues/14090#issuecomment-922327377.
This breaks loading the adapters because it relies only on `&rtp`.

This is fixing it for me:
```diff
diff --git a/autoload/db/adapter.vim b/autoload/db/adapter.vim
index a47c32e..3c4141c 100644
--- a/autoload/db/adapter.vim
+++ b/autoload/db/adapter.vim
@@ -21,9 +21,13 @@ function! s:prefix(url) abort
     let prefix = 'db#adapter#'.adapter.'#'
   endif
   let file = 'autoload/'.substitute(tr(prefix, '#', '/'), '/[^/]*$', '.vim', '')
+  let rtp = &rtp
+  if has('nvim-0.5.1')
+    let rtp = join(nvim_get_runtime_file('', v:true), ',')
+  endif
   if has_key(s:loaded, adapter) || prefix !~# '#'
     return prefix
-  elseif !empty(findfile(file, escape(&rtp, ' ')))
+  elseif !empty(findfile(file, escape(rtp, ' ')))
     execute 'runtime!' file
     let s:loaded[adapter] = 1
     return prefix
@@ -58,8 +62,12 @@ function! db#adapter#dispatch(url, fn, ...) abort
 endfunction
 
 function! db#adapter#schemes() abort
+  let rtp = &rtp
+  if has('nvim-0.5.1')
+    let rtp = join(nvim_get_runtime_file('', v:true), ',')
+  endif
   return map(
-        \ split(globpath(escape(&rtp, ' '), 'autoload/db/adapter/*.vim'), "\n"),
+        \ split(globpath(escape(rtp, ' '), 'autoload/db/adapter/*.vim'), "\n"),
         \ 'tr(fnamemodify(v:val, ":t:r"), "_", "-")') +
         \ filter(map(keys(g:), 'matchstr(v:val, "^db_adapter_\\zs.*")'), 'len(v:val)')
 endfunction
```

But it's not too pretty. 
Do you want me to make a PR or you will take care of this?

**Comment by tpope** [comment]
The use of `nvim_get_runtime_file('', v:true)` here feels unnecessarily convoluted. The first change would better be served with `!empty(nvim_get_runtime_file(file, v:false))`, and the second should probably call `nvim_list_runtime_paths()`. And check for the existence of the those functions directly rather than the lie that is `has('nvim-0.5.1')`.

Regardless, given the nature of Neovim master, I'm inclined to sit on this a couple of weeks and see what else shakes out. But if you send a PR with those changes I'm willing to accelerate the schedule.
